<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net6.0;net8.0;net35</TargetFrameworks>
    <Title>Kavenegar</Title>
    <PackageId>Kavenegar</PackageId>
    <OutputType>Library</OutputType>
    <Description>Kavenegar API in .NET</Description>
    <Authors>Kavenegar Team, Bagher Sohrabi, Ardavan</Authors>
    <PackageTags>REST; SMS; voice; TTS; OTP; API; Verification; kavenegar; Voicesms</PackageTags>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageProjectUrl>https://github.com/kavenegar/kavenegar-dotnet</PackageProjectUrl>
    <RepositoryUrl>https://github.com/kavenegar/kavenegar-dotnet</RepositoryUrl>
    <Version>1.1.5-alpha.1</Version>
    <PackageReleaseNotes>Force SSL</PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(NETCoreSdkVersion)' != '' And $(NETCoreSdkVersion.StartsWith('10.')) ">
    <TargetFrameworks>netstandard2.0;net6.0;net8.0;net10.0;net35</TargetFrameworks>
  </PropertyGroup>

  <!-- Conditionally obtain references for .NET Framework targets -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'net35' Or '$(TargetFramework)' == 'net45' Or '$(TargetFramework)' == 'net451' Or '$(TargetFramework)' == 'net452' Or '$(TargetFramework)' == 'net46' Or '$(TargetFramework)' == 'net461' Or '$(TargetFramework)' == 'net462' Or '$(TargetFramework)' == 'net47' Or '$(TargetFramework)' == 'net471' Or '$(TargetFramework)' == 'net472' Or '$(TargetFramework)' == 'net48' Or '$(TargetFramework)' == 'net481' ">
    <Reference Include="System.Web" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>

</Project>